name: Code CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
  
jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "2.7"
        
      - name: Install linter
        run: pip install flake8 black[python2]

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Lint with black
        run: |
          black --check .
