name: Code CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    container:
      image: python:2.7.18-buster
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pip3
        run: |
          apt-get update
          apt-get install -y python3-pip

      - name: Install linters
        run: |
          pip install flake8
          pip3 install black[python2]

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Lint with black
        run: |
          black --check .
